### ISSUE TITLE
Best serialization for xgboost?

### ISSUE THREAD

**Issue by juliasilge** [rstudio/bundle#43]
Right now we are using `xgboost::xgb.serialize()` but I thought that `xgb.save.raw()` was the best option (more portable).

@simonpcouch did you look into these or compare them?

**Comment by simonpcouch** [comment]
From what I read, I also came to the conclusion that `xgb.save.raw()` was more portable, and that `xgb.serialize()` would preserve more functionality after loading since that `params` object is brought along. Since the scope of bundle at this point is more focused (to _just_ preserve prediction) I agree that `xgb.save.raw()` is the best option. :)
