### ISSUE TITLE
Will bundle support fable, feasts, and prophet packages? 

### ISSUE THREAD

**Issue by lbui30** [rstudio/bundle#49]
Bundle seems like an amazing package, does any of it work with feasts or the prophet package?  I have some test data and a reproducible example if anyone is willing to work on this.

**Comment by lbui30** [comment]
I created a reproducible example as I think that bundle may solve the core issue that I am having.
Hopefully, the Rstudio post gets approved, so you can understand the context of the problem better: 
[https://community.rstudio.com/t/why-wont-my-prophet-fable-model-with-holidays-forecast-in-a-new-r-environment/153767/1](https://community.rstudio.com/t/why-wont-my-prophet-fable-model-with-holidays-forecast-in-a-new-r-environment/153767/1)

I will also next create follow-up issue posts in both prophet and fable packages to inform the authors.

**Comment by juliasilge** [comment]
We are definitely open to working on making it possible to load these types of models in a new session for predicting! However, it is not clear to me what part of your code is responsible for the model not working in a new session. 

It would be very helpful if you can work on making a much simpler reprex showing how this fails (no reading from a database, do not use all three of these at once but rather one at a time, etc). You can [take a look at the examples](https://rstudio.github.io/bundle/reference/index.html) already in bundle for inspiration of how complex the example should be, or [this blog post](https://www.tidyverse.org/blog/2022/09/bundle-0-1-0/). I am wondering if the problem is with the database connection, not with these models, and a much simpler reprex will help!

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
