### ISSUE TITLE
Error when using a bundled Keras model on POSIT Workbench

### ISSUE THREAD

**Issue by andrewbcooper** [rstudio/bundle#71]
Hello!  Thank yo for this amazing packages!  I trained a Keras model on my laptop, bundled it, uploaded it to our POSIT Workbench environment, and then tried to use it for predictions.  Unfortunately, I got the error:

Error in if (tensorflow::tf_version() < "2.0.0") stop("TensorFlow version >= 2.0.0 is requires to load models in the SavedModel format.",  : 
  argument is of length zero

My guess it's because we don't actually have TensorFlow installed on the POSIT Workbench servers (e.g., install_tensorflow(); install_keras()) even though we have both TensorFlow and Keras packages installed.  tensorflow::tf_version() returns NULL.

Is there any way to use bundle to get predictions from a Keras model without installing TensorFlow / Keras?  Our IT folks say it'll probably be 6-9 months before they can get around to that :/

Thanks!

Non-reproducable code:

On my laptop:

bundled_NNModel <-
  bundle(NNModel)

save(bundled_NNModel,file="bundled_NNModel.RData")

After uploading to the server....

load("bundled_NNModel.RData")
library(keras)

r(
  function(model_bundle, new_data) {
    library(bundle)
    
    model_object <- unbundle(model_bundle)
    
    predict(model_object, new_data)
  },
  args = list(
    model_bundle = bundled_NNModel,
    new_data = as.matrix(testfeatures)
  )
)

**Comment by juliasilge** [comment]
Unfortunately, bundling only solves the problem of [how you serialize your model](https://rstudio.github.io/bundle/articles/bundle.html), not the software that you then need to use the model. For example, you likely will need bundle to store an xgboost model and use it in a new R session because of how xgboost works, but you _also still need xgboost_.

An option for making predictions that does not require the original R package is [orbital](https://orbital.tidymodels.org/), but currently it [does not provide support for keras models](https://orbital.tidymodels.org/articles/supported-models.html).

**Comment by andrewbcooper** [comment]
Thank you for your lightning-fast response!  That's kind of what I figured.  Thankfully, it looks like I can get around it by using torch and luz which don't require IT to do anything :)  And even more thankfully, your bundle package handles those beautifully!  Thanks for this amazing package!

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
